# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2685a2fcca44b9c8ad52bc3efeca773e28e9feb9cf3da99eb8cbe4db8bf9be0bd5239ead274b5ef80fa0ecc51a8d572de48cf93428579a94c5f516d8933c0855

test:
  secret_key_base: dd084506e8a02ba1a28708a93c49daadf3787c3169522ba7cdef95a5cf857ad06b6b0eb0cdd220c376a7c8b742452eebb697f6133b2f3b31c8d7ee6392888ed8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
